resource_group_name  = "rg-terraform-state-test"
storage_account_name = "uqhaztfstatetest"
container_name       = "tfstate"
key                  = "terraform-infra-test-day-3.tfstate"
subscription_id      = "782871a0-bcee-44fb-851f-ccd3e69ada2a"