resource_group_name  = "rg-terraform-state-dev"
storage_account_name = "uqhaztfstatedev"
container_name       = "tfstate"
key                  = "terraform-infra-dev-day-3.tfstate"
subscription_id      = "be4e82ff-bf83-4173-a750-15e807845579"