applicationsets:
  chat:
    additionalAnnotations:
      argocd.argoproj.io/sync-wave: "1"
    namespace: unique
    goTemplate: true
    generators:
      - git:
          repoURL: https://github.com/Unique-AG/hello-azure
          revision: preview
          files:
          - path: "applications/dev/apps/chat/*.yaml"
    template:
      metadata:
        name: '{{ .spec.name }}'
        namespace: unique
      spec:
        project: default
        destination:
          server: https://kubernetes.default.svc
          namespace: unique
    templatePatch: |
      spec:
        {{- if hasKey .spec "sources" }}
        sources:
          {{- .spec.sources | toYaml | nindent 4 }}
        {{- else }}
        source:
          {{- .spec.source | toYaml | nindent 4 }}
        {{- end }}
        {{- if hasKey .spec "additionalValues" }}
        {{- .spec.additionalValues | toYaml | nindent 2 }}
        {{- end }}
        {{- if hasKey .spec "ignoreDifferences" }}
        ignoreDifferences:
          {{- .spec.ignoreDifferences | toYaml | nindent 4 }}
        {{- end }}
        {{- if .spec.autoSync }}
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
          syncOptions:
            - CreateNamespace=true
        {{- end }}


  system:
    additionalAnnotations:
      argocd.argoproj.io/sync-wave: "0"
    namespace: unique
    goTemplate: true
    generators:
    - git:
        repoURL: https://github.com/Unique-AG/hello-azure
        revision: preview
        files:
        - path: "applications/dev/apps/system/*.yaml"
    template:
      metadata:
        name: '{{ .spec.name }}'
        namespace: unique
      spec:
        project: default
        destination:
          server: https://kubernetes.default.svc
          namespace: unique
    templatePatch: |
      spec:
        {{- if hasKey .spec "sources" }}
        sources:
          {{- .spec.sources | toYaml | nindent 4 }}
        {{- else }}
        source:
          {{- .spec.source | toYaml | nindent 4 }}
        {{- end }}
        {{- if hasKey .spec "additionalValues" }}
        {{- .spec.additionalValues | toYaml | nindent 2 }}
        {{- end }}
        {{- if hasKey .spec "ignoreDifferences" }}
        ignoreDifferences:
          {{- .spec.ignoreDifferences | toYaml | nindent 4 }}
        {{- end }}
        {{- if .spec.autoSync }}
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
          syncOptions:
            - CreateNamespace=true
        {{- end }}