name: "[tf] [test] Infrastructure Plan 🏗️"
on:
  pull_request:
    branches:
      - preview
      - '!release'
      - '!main'
    paths:
      - .github/workflows/test.infrastructure.tf.plan.yaml
      - 02_infrastructure/**/*.tf
      - terraform-modules/**
  push:
    branches:
      - preview
    paths:
      - .github/workflows/test.infrastructure.tf.plan.yaml
      - 02_infrastructure/**/*.tf
      - terraform-modules/**
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write # To write comments
  id-token: write

jobs:
  automated-plan-apply:
    environment: 10-pm
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: 02_infrastructure/day-3
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 #v4.0.0
        with:
          terraform_version: 1.12.0

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init -backend-config=../environments/test/backend-config-day-3.hcl

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -var-file=../environments/test/00-config-day-3.auto.tfvars -var-file=../environments/test/00-parameters-day-3.auto.tfvars -no-color
